version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "15:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gulp-notify
    versions:
    - 4.0.0
  - dependency-name: gulp-sourcemaps
    versions:
    - 3.0.0
  - dependency-name: gulp-rename
    versions:
    - 2.0.0
  - dependency-name: gulp-autoprefixer
    versions:
    - 7.0.1
  - dependency-name: gulp-cssnano
    versions:
    - 2.1.3
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: yargs-parser
    versions:
    - 5.0.1
