baseurl = "https://example.org"
languageCode = "en-US"
title = "Sarah theme demo"
theme = "sarah"
googleAnalytics = ""
disqusShortname = ""

[params]
author = "Sarah Theme"
keywords = ["hugo-theme-sarah", "Hugo Theme", "Hugo"]
description = "Sarah theme for Hugo static site generator"
avatar = "https://github.com/avelino/hugo-theme-sarah/raw/master/images/projects.png"
dateform = "Jan 2, 2006"
lang = "en"
footertext = "written by avelino"
about = """
hugo-theme-sarah about
"""

[params.social]
instagram     = "avelinorun"
github        = "avelino"
twitter       = "avelinorun"
linkedin      = "avelinorun"

[[params.info]]
label = "Address"
value = "github.com/avelino/hugo-theme-sarah"

[[params.projects]]
name = "Sarah Theme"
desc = "Sarah theme for Hugo static site generator"
img = "https://github.com/avelino/hugo-theme-sarah/raw/master/images/screenshot.png"
link = "https://github.com/avelino/hugo-theme-sarah"
