name: Grunt build and commit updated stylesheets (main branch)

on: [push, pull_request]

jobs:
  grunt-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: npm ci
      - run: gulp build
